import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { QrCode, ArrowLeft, CheckCircle } from 'lucide-react';
import { useCheckout } from '../contexts/CheckoutContext';
import Header from '../components/Header';

const UPIPayment = () => {
  const navigate = useNavigate();
  const { total } = useCheckout();
  const [paymentMethod, setPaymentMethod] = useState('qr'); // 'qr' or 'upi'
  const [upiId, setUpiId] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [error, setError] = useState('');

  // Mock QR Code (in production, this would be generated by payment gateway)
  const mockQRCode = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2ZmZiIvPjxyZWN0IHg9IjEwIiB5PSIxMCIgd2lkdGg9IjE4MCIgaGVpZ2h0PSIxODAiIGZpbGw9IiMwMDAiLz48L3N2Zz4=';

  const handleVerifyUPI = async () => {
    if (!upiId) {
      setError('Please enter UPI ID');
      return;
    }

    if (!/^[\w.-]+@[\w.-]+$/.test(upiId)) {
      setError('Invalid UPI ID format');
      return;
    }

    setIsVerifying(true);
    setError('');

    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Mock successful verification
    setIsVerifying(false);
    navigate('/order-confirmation', { state: { paymentMethod: 'upi', upiId } });
  };

  const handleQRPayment = async () => {
    // In production, you'd verify payment status via webhook
    // For demo, simulate payment after 3 seconds
    await new Promise(resolve => setTimeout(resolve, 3000));
    navigate('/order-confirmation', { state: { paymentMethod: 'upi-qr' } });
  };

  return (
    <div className="min-h-screen bg-white">
      <Header />
      
      <div className="max-w-3xl mx-auto px-6 py-24 mt-16">
        {/* Back Button */}
        <button
          onClick={() => navigate('/payment')}
          className="flex items-center gap-2 text-sm text-gray-600 hover:text-black mb-8"
        >
          <ArrowLeft size={16} />
          Back to payment options
        </button>

        {/* Title */}
        <motion.h1 
          className="text-4xl md:text-5xl tracking-[0.3em] mb-12"
          style={{ fontFamily: 'Didot, serif' }}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          UPI PAYMENT
        </motion.h1>

        {/* Total Amount */}
        <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 p-6 mb-8 rounded-lg">
          <div className="flex justify-between items-center">
            <span className="text-lg font-medium">Total Amount</span>
            <span className="text-4xl font-bold">${total.toFixed(2)}</span>
          </div>
        </div>

        {/* Payment Method Tabs */}
        <div className="flex gap-4 mb-8">
          <button
            onClick={() => setPaymentMethod('qr')}
            className={`flex-1 py-3 text-sm tracking-wider font-medium border-b-2 transition-colors ${
              paymentMethod === 'qr'
                ? 'border-black text-black'
                : 'border-gray-300 text-gray-500 hover:text-gray-700'
            }`}
          >
            SCAN QR CODE
          </button>
          <button
            onClick={() => setPaymentMethod('upi')}
            className={`flex-1 py-3 text-sm tracking-wider font-medium border-b-2 transition-colors ${
              paymentMethod === 'upi'
                ? 'border-black text-black'
                : 'border-gray-300 text-gray-500 hover:text-gray-700'
            }`}
          >
            ENTER UPI ID
          </button>
        </div>

        <AnimatePresence mode="wait">
          {/* QR Code Payment */}
          {paymentMethod === 'qr' && (
            <motion.div
              key="qr"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              className="bg-white border-2 border-gray-200 rounded-lg p-8"
            >
              {/* QR Code */}
              <div className="flex flex-col items-center mb-6">
                <div className="bg-white p-6 rounded-lg shadow-lg border-4 border-black mb-4">
                  <img 
                    src={mockQRCode} 
                    alt="Payment QR Code" 
                    className="w-64 h-64"
                  />
                </div>
                <p className="text-sm text-gray-600 text-center mb-2">
                  Scan this QR code with any UPI app
                </p>
                <div className="flex items-center gap-3 text-xs text-gray-500">
                  <span>Google Pay</span>
                  <span>•</span>
                  <span>PhonePe</span>
                  <span>•</span>
                  <span>Paytm</span>
                  <span>•</span>
                  <span>BHIM</span>
                </div>
              </div>

              {/* Instructions */}
              <div className="bg-blue-50 border border-blue-200 rounded p-4 mb-6">
                <h4 className="font-medium mb-2 text-sm">How to pay:</h4>
                <ol className="text-sm text-gray-700 space-y-1 list-decimal list-inside">
                  <li>Open your UPI app</li>
                  <li>Tap on "Scan & Pay"</li>
                  <li>Scan the QR code above</li>
                  <li>Verify the amount and confirm payment</li>
                </ol>
              </div>

              {/* Demo Button - Remove in production */}
              <button
                onClick={handleQRPayment}
                className="w-full bg-black text-white py-4 text-xs tracking-[0.3em] hover:bg-gray-800 transition-colors"
              >
                SIMULATE PAYMENT (DEMO)
              </button>

              <p className="text-xs text-center text-gray-500 mt-4">
                Waiting for payment confirmation...
              </p>
            </motion.div>
          )}

          {/* UPI ID Payment */}
          {paymentMethod === 'upi' && (
            <motion.div
              key="upi"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="bg-white border-2 border-gray-200 rounded-lg p-8"
            >
              {/* UPI ID Input */}
              <div className="mb-6">
                <label className="block text-sm font-medium mb-2">
                  Enter your UPI ID
                </label>
                <input
                  type="text"
                  value={upiId}
                  onChange={(e) => {
                    setUpiId(e.target.value);
                    setError('');
                  }}
                  placeholder="yourname@upi"
                  className={`w-full px-4 py-3 border-2 ${
                    error ? 'border-red-500' : 'border-gray-300'
                  } focus:outline-none focus:border-black text-lg rounded`}
                />
                {error && (
                  <p className="text-sm text-red-600 mt-2">{error}</p>
                )}
                <p className="text-xs text-gray-500 mt-2">
                  Example: 9876543210@paytm or yourname@okaxis
                </p>
              </div>

              {/* Popular UPI Apps */}
              <div className="bg-gray-50 rounded p-4 mb-6">
                <h4 className="text-sm font-medium mb-3">Popular UPI handles:</h4>
                <div className="grid grid-cols-2 gap-2 text-sm text-gray-700">
                  <div>• @paytm</div>
                  <div>• @phonepe</div>
                  <div>• @okaxis</div>
                  <div>• @ybl</div>
                  <div>• @oksbi</div>
                  <div>• @okicici</div>
                </div>
              </div>

              {/* Verify Button */}
              <button
                onClick={handleVerifyUPI}
                disabled={isVerifying}
                className="w-full bg-black text-white py-4 text-xs tracking-[0.3em] hover:bg-gray-800 transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isVerifying ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    VERIFYING...
                  </>
                ) : (
                  'VERIFY & PAY'
                )}
              </button>

              {/* Security Note */}
              <div className="mt-6 bg-green-50 border border-green-200 rounded p-4">
                <div className="flex items-start gap-2">
                  <CheckCircle size={16} className="text-green-600 mt-0.5" />
                  <div className="text-xs text-green-800">
                    <p className="font-medium mb-1">Safe & Secure</p>
                    <p>Your UPI ID will be verified before proceeding with payment</p>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Help Text */}
        <div className="mt-8 text-center">
          <p className="text-xs text-gray-500">
            Having trouble? Contact support for assistance
          </p>
        </div>
      </div>
    </div>
  );
};

export default UPIPayment;
